### ISSUE TITLE
Issues with custom transformer serialization

### ISSUE THREAD

**Issue by llKetanll** [combust/mleap#616] opened 2019-12-16 17:40 UTC
I ran into this exception and don't seem to be able to identify the root cause. Am I missing any dependencies?
 
Project Structure:
```
.
├── build.sbt
├── project
│   ├── Dependencies.scala
│   ├── xyzProject.scala
│   ├── build.properties
│   ├── plugins.sbt
├── xyz-core
│   ├── build.sbt
│   ├── src
│   │   ├── main
│   │   │   └── scala
│   │   │       └── com
│   │   │           └── abc
│   │   │               └── xyz
│   │   │                   └── core
│   │   │                       ├── features
│   │   │                       │   ├── Timestamp.scala
│   │   │                       └── utils
│   │   │                           └── DateUtil.scala
├── xyz-examples
│   ├── build.sbt
│   ├── src
│   │   ├── main
│   │   │   └── scala
│   │   │       └── com
│   │   │           └── abc
│   │   │               └── xyz
│   │   │                   └── examples
│   │   │                       └── TimestampFeatureExtractor.scala
├── xyz-mleap
│   ├── build.sbt
│   ├── src
│   │   ├── main
│   │   │   ├── resources
│   │   │   │   └── reference.conf
│   │   │   └── scala
│   │   │       └── com
│   │   │           └── abc
│   │   │               └── xyz
│   │   │                   └── mleap
│   │   │                       ├── ops
│   │   │                       │   └── TimestampFeaturizerOp.scala
│   │   │                       └── transformer
│   │   │                           └── TimestampFeaturizer.scala
├── xyz-spark
│   ├── build.sbt
│   ├── src
│   │   ├── main
│   │   │   ├── resources
│   │   │   │   └── reference.conf
│   │   │   └── scala
│   │   │       ├── com
│   │   │       │   └── abc
│   │   │       │       └── xyz
│   │   │       │           └── spark
│   │   │       │               ├── ops
│   │   │       │               │   └── TimestampFeaturizerOp.scala
│   │   │       │               └── transformer
│   │   │       │                   └── TimestampFeaturizer.scala
└── version.sbt
```

Dependencies for `xyz-spark`

```
libraryDependencies ++= Seq(
    "org.apache.spark" %% "spark-core" % "2.4.4",
    "org.apache.spark" %% "spark-sql" % "2.4.4",
    "org.apache.spark" %% "spark-mllib" % "2.4.4",
    "ml.combust.mleap" %% "mleap-spark" % "0.15.0",
    "ml.combust.mleap" %% "mleap-spark-extension" % "0.15.0"
)
```

Dependencies for `xyz-mleap`

```
libraryDependencies ++= Seq(
    "ml.combust.mleap" %% "mleap-runtime" % "0.15.0"
)
```

Dependencies for `xyz-examples`

```
libraryDependencies ++= Seq(
    "org.apache.spark" %% "spark-core" % "2.4.4",
    "org.apache.spark" %% "spark-sql" % "2.4.4",
)
```

Content for `xyz-spark/src/main/resources/reference.conf`
```
com.abc.xyz.spark.ops = [
    "com.abc.xyz.spark.ops.TimestampFeaturizerOp"
]

ml.combust.mleap.spark.registry.default += com.abc.xyz.spark.ops
```

Content for `xyz-mleap/src/main/resources/reference.conf`
```
com.abc.xyz.mleap.ops = [
    "com.abc.xyz.mleap.ops.TimestampFeaturizerOp",
]

ml.combust.mleap.registry.default.ops += "com.abc.xyz.mleap.ops"
```

Content for `xyz-examples/src/main/scala/com/abc/xyz/TimestampFeatureExtractor.scala`
```
package com.abc.xyz.examples

import resource._
import ml.combust.bundle.BundleFile
import org.apache.spark.ml.mleap.SparkUtil
import ml.combust.mleap.spark.SparkSupport._
import org.apache.spark.ml.bundle.SparkBundleContext
import org.apache.spark.SparkConf
import org.apache.spark.ml.{Pipeline, Transformer}
import org.apache.spark.sql.{DataFrame, SparkSession}
import com.abc.xyz.spark.transformer.TimestampFeaturizer
import ml.combust.bundle.serializer.SerializationFormat


object TimestampFeatureExtractor {
    def main(args: Array[String]): Unit = {
        // initialize spark
        val conf = new SparkConf().setAppName("DateTransformer").setMaster("local")
        val spark = SparkSession.builder().config(conf).getOrCreate()
        import spark.implicits._

        val training = Seq(
            ("1", "2018-01-05T09:00:00.000"),
            ("2", "2019-03-15T09:00:00.000"),
            ("3", "2017-05-17T09:00:00.000"),
            ("4", "2015-06-23T09:00:00.000"),
            ("5", "2018-04-11T09:00:00.000"),
            ("6", "2019-11-01T09:00:00.000")).toDF("uid", "timestampColumn")
        training.show()

        val tsFeaturizer: Transformer = new TimestampFeaturizer().setTimestampCol("timestampColumn")
        val pipeline = new Pipeline().setStages(Array(tsFeaturizer))
        val model = pipeline.fit(training)

        val test = training
        model.transform(test).show()

        val mleapPipeline = SparkUtil.createPipelineModel(uid = "pipeline", Array(model))
        val sbc = SparkBundleContext()
        for (bundle <- managed(BundleFile("jar:file:/Users/ketankumar/tmp/models/TimestampFeatureExtractor.zip"))) {
            mleapPipeline.writeBundle.format(SerializationFormat.Json).save(bundle)(sbc).get
        }
    }
}
```

```
Exception in thread "main" java.util.NoSuchElementException: key not found: org.apache.spark.ml.PipelineModel
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at ml.combust.bundle.BundleRegistry.opForObj(BundleRegistry.scala:102)
	at ml.combust.bundle.BundleWriter$$anonfun$1.apply(BundleWriter.scala:28)
	at ml.combust.bundle.BundleWriter$$anonfun$1.apply(BundleWriter.scala:28)
	at scala.Option.getOrElse(Option.scala:121)
	at ml.combust.bundle.BundleWriter.save(BundleWriter.scala:27)
	at com.abc.xyz.examples.TimestampFeatureExtractor$$anonfun$main$2.apply(TimestampFeatureExtractor.scala:51)
	at com.abc.xyz.examples.TimestampFeatureExtractor$$anonfun$main$2.apply(TimestampFeatureExtractor.scala:50)
	at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:88)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
	at scala.util.control.Exception$Catch.apply(Exception.scala:103)
	at scala.util.control.Exception$Catch.either(Exception.scala:125)
	at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:88)
	at resource.ManagedResourceOperations$class.apply(ManagedResourceOperations.scala:26)
	at resource.AbstractManagedResource.apply(AbstractManagedResource.scala:50)
	at resource.ManagedResourceOperations$class.acquireAndGet(ManagedResourceOperations.scala:25)
	at resource.AbstractManagedResource.acquireAndGet(AbstractManagedResource.scala:50)
	at resource.ManagedResourceOperations$class.foreach(ManagedResourceOperations.scala:53)
	at resource.AbstractManagedResource.foreach(AbstractManagedResource.scala:50)
	at com.abc.xyz.examples.TimestampFeatureExtractor$.main(TimestampFeatureExtractor.scala:50)
	at com.abc.xyz.examples.TimestampFeatureExtractor.main(TimestampFeatureExtractor.scala)
```

**Comment by ancasarb** [comment] 2020-01-20 19:06
Does the subproject xyz-examples depend on xyz-spark? 

Also, small note, 

it is enough to do

```
libraryDependencies ++= Seq(
    "org.apache.spark" %% "spark-core" % "2.4.4",
    "org.apache.spark" %% "spark-sql" % "2.4.4",
    "org.apache.spark" %% "spark-mllib" % "2.4.4",
    "ml.combust.mleap" %% "mleap-spark-extension" % "0.15.0"
)
```

instead of 

```
libraryDependencies ++= Seq(
    "org.apache.spark" %% "spark-core" % "2.4.4",
    "org.apache.spark" %% "spark-sql" % "2.4.4",
    "org.apache.spark" %% "spark-mllib" % "2.4.4",
    "ml.combust.mleap" %% "mleap-spark" % "0.15.0",
    "ml.combust.mleap" %% "mleap-spark-extension" % "0.15.0"
)
```

mleap-spark is brought in as a transitive dependency for mleap-spark-extension.

**Comment by ancasarb** [comment] 2020-01-20 19:09
And actually, 

```
ml.combust.mleap.spark.registry.default += com.abc.xyz.spark.ops
```

needs to be 

```
ml.combust.mleap.spark.registry.default.ops += com.abc.xyz.spark.ops
```

see the added ".ops" at the end of the default spark registry.

I am thinking this is possibly the cause of your issues.

**Comment by ancasarb** [comment] 2020-05-01 21:40
I believe the fix above should get the custom transformer working so I will close this issue for now. Please re-open it if you are still seeing issues, thank you!

**Closed by ancasarb** 2020-05-01 21:40 UTC
