### ISSUE TITLE
lightweight dependency

### ISSUE THREAD

**Issue by NetanelRabinowitz** [combust/mleap#293] opened 2017-10-23 16:01 UTC
Is it possible to build only the necessary modules for online evaluation of the model?  If so, is it possible to do it for scala 2.12?

**Comment by hollinwilkins** [comment] 2017-10-25 04:34
@NetanelRabinowitz Hey, do you mean all of the models in mleap-core? We can get them building, but it will take a little bit of work.

We currently only build for 2.10 and 2.11. We need to get `sbt-doge` working in order to build modules across more versions of Scala.

The reason we need `sbt-doge` is because mleap-spark requires scala versions 2.10 and 2.11 in order to support Spark 2.0 and up. Building cross-versions for specific submodules is not supported out of the box by SBT. `sbt-doge` provides support for change cross-versions between different submodules, but breaks our build for reasons we can go into more if you are interested.

We would very much like to support this, and we need to moving forward!

**Comment by NetanelRabinowitz** [comment] 2017-10-26 08:38
@hollinwilkins I meant for mleap-runtime as a standalone jar. anyway for now 2.12 is awesome anyway :) it seems like mleap is the way to go for us, but in order to get it into production we need 2.12. please do share the details, maybe I can get my hands on it and help. 
Thanks!

**Comment by hollinwilkins** [comment] 2017-10-26 19:29
@NetanelRabinowitz `sbt-doge` I am pretty sure is the way to go. We have got it working a couple of times now. The only issue is that it breaks our build because of some issue with `sbt-pgp`, which we rely on for signing our artifacts before we deliver them to maven central.

**Comment by hollinwilkins** [comment] 2017-10-26 19:29
@ancasarb May have some more details on exactly what the issue is too

**Comment by ancasarb** [comment] 2017-10-27 14:36
@hollinwilkins  I will try to get it working this weekend and let you know what are my findings.

**Comment by NetanelRabinowitz** [comment] 2017-10-31 07:36
@ancasarb any updates? how did you overcome the fact that the runtime depends on `spark-mllib-local` but it available only for scala 2.11?

**Comment by ancasarb** [comment] 2017-10-31 10:58
@NetanelRabinowitz this is how we were trying to use sbt-doge plugin to build mleap-scoring only for scala 2.11 and not scala 2.10. 

https://github.com/combust/mleap/compare/master...ancasarb:mleap_serving_project?expand=1

This unfortunately breaks the publishing of artifacts, as Hollin was saying, which is what I am looking at the moment.

**Comment by hollinwilkins** [comment] 2017-10-31 15:05
@NetanelRabinowitz We will have to get rid of spark-mllib-local as a dependency. This should be pretty straightforward to do, as most of the functionality is already in Breeze. It will be some work though because of the number of models that depend on it. Would you be interested in having a look at this?

**Comment by NetanelRabinowitz** [comment] 2017-11-03 11:11
I will. Thanks!

**Comment by hollinwilkins** [comment] 2017-11-08 00:49
@NetanelRabinowitz Great, let me know how it's going or if you need anything. This would be a very welcome refactoring of code.

**Comment by ancasarb** [comment] 2019-05-02 15:53
Closing this issue, as we're adding support for scala 2.12 here https://github.com/combust/mleap/pull/496 and tracking it here https://github.com/combust/mleap/issues/445. Please re-open if you think adding support 2.12 is not enough for what you had in mind, thanks!

**Closed by ancasarb** 2019-05-02 15:53 UTC
