### ISSUE TITLE
Mleap-server, model loading error 

### ISSUE THREAD

**Issue by manugarri** [combust/mleap#182] opened 2017-04-20 10:24 UTC
I am following the example [here](https://github.com/combust/mleap-demo/blob/master/notebooks/airbnb-price-regression.ipynb) with my own dataset. 

It works all the way till the serializing/deserializing with no problems.

However, when I am loading the model on a running mleap-server as explained [here](http://mleap-docs.combust.ml/mleap-serving/#load-model) , it fails with the error.

```
[ERROR] [04/20/2017 12:22:19.020] [MleapServing-akka.actor.default-dispatcher-13] [MleapResource] error with request
java.nio.file.NoSuchFileException: bundle.json
        at com.sun.nio.zipfs.ZipFileSystem.newInputStream(ZipFileSystem.java:544)
        at com.sun.nio.zipfs.ZipPath.newInputStream(ZipPath.java:645)
        at com.sun.nio.zipfs.ZipFileSystemProvider.newInputStream(ZipFileSystemProvider.java:278)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at ml.combust.bundle.BundleFile$$anonfun$readInfo$1.apply(BundleFile.scala:60)
        at ml.combust.bundle.BundleFile$$anonfun$readInfo$1.apply(BundleFile.scala:60)
        at resource.DefaultManagedResource.open(AbstractManagedResource.scala:110)
        at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:87)
        at resource.ManagedResourceOperations$class.apply(ManagedResourceOperations.scala:26)
        at resource.AbstractManagedResource.apply(AbstractManagedResource.scala:50)
        at resource.DeferredExtractableManagedResource$$anonfun$tried$1.apply(AbstractManagedResource.scala:33)
        at scala.util.Try$.apply(Try.scala:192)
        at resource.DeferredExtractableManagedResource.tried(AbstractManagedResource.scala:33)
        at ml.combust.bundle.BundleFile.readInfo(BundleFile.scala:63)
        at ml.combust.bundle.serializer.BundleSerializer.read(BundleSerializer.scala:49)
        at ml.combust.bundle.BundleFile.load(BundleFile.scala:87)
        at ml.combust.mleap.runtime.MleapSupport$MleapBundleFileOps.loadMleapBundle(MleapSupport.scala:18)
        at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2$$anonfun$apply$2.apply(MleapService.scala:28)
        at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2$$anonfun$apply$2.apply(MleapService.scala:27)
        at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:88)
        at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
        at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
        at scala.util.control.Exception$Catch.apply(Exception.scala:103)
        at scala.util.control.Exception$Catch.either(Exception.scala:125)
        at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:88)
        at resource.ManagedResourceOperations$class.apply(ManagedResourceOperations.scala:26)
        at resource.AbstractManagedResource.apply(AbstractManagedResource.scala:50)
        at resource.DeferredExtractableManagedResource$$anonfun$tried$1.apply(AbstractManagedResource.scala:33)
        at scala.util.Try$.apply(Try.scala:192)
        at resource.DeferredExtractableManagedResource.tried(AbstractManagedResource.scala:33)
        at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2.apply(MleapService.scala:29)
        at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2.apply(MleapService.scala:29)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[ERROR] [04/20/2017 12:22:19.021] [MleapServing-akka.actor.default-dispatcher-13] [akka.actor.ActorSystemImpl(MleapServing)] Error during processing of request: 'bundle.json'. Completing with 500 Internal Server Error response.
```

The file `bundle.json` exists in the zipfile alongside the `root` folder. The airbnb Random Forest model example fails as well (loading it with `curl -X PUT -H "content-type: application/json"   -d '{"path":"airbnb.model.rf-0.6.0-SNAPSHOT.zip"}'   http://localhost:65327/model` with the same error.

**Comment by hollinwilkins** [comment] 2017-04-20 17:35
@manugarri Hey, make sure that your model is serializing successfully by unwrapping all Try objects that you are getting back. Often there is an error serializing the pipeline because of a OneHotEncoder.

**Comment by hollinwilkins** [comment] 2017-04-20 17:36
Would you mind sharing your model zip file or at least the tree structure of it here, including all files/subdirectories?

**Comment by smaxwellstewart** [comment] 2017-05-18 20:23
I have created a very simple model just to test the basically functionality of MLeap but I am getting the same error as above.

My Mleap model:
[simple-json.zip](https://github.com/combust/mleap/files/1012345/simple-json.zip)


Here is my mleap code to create that model:

```scala
import ml.combust.bundle.BundleFile
import ml.combust.bundle.serializer.SerializationFormat
import org.apache.spark.ml.feature.{StringIndexerModel, VectorAssembler}
import org.apache.spark.ml.mleap.SparkUtil
import ml.combust.mleap.spark.SparkSupport._
import resource._

// Create a sample pipeline that we will serialize
// And then deserialize using various formats
val stringIndexer = new StringIndexerModel(labels = Array("Hello, MLeap!", "Another row")).
  setInputCol("a_string").
  setOutputCol("a_string_index")
val featureAssembler = new VectorAssembler().setInputCols(Array("a_double")).
  setOutputCol("features")

// Because of Spark's privacy, our example pipeline is considerably
// Less interesting than the one we used to demonstrate MLeap serialization
val pipeline = SparkUtil.createPipelineModel(Array(stringIndexer, featureAssembler))

for(bundle <- managed(BundleFile("jar:file:/tmp/simple-json.zip"))) {
  pipeline.writeBundle.format(SerializationFormat.Json).save(bundle)
}
```

This works fine (though strangely i get an error when I try and unzip on my mac). I then mount this file inside my docker container running mleap, so it can be found under `/models/simple-json.zip`. And try and load the model by running:

```bash
curl -XPUT -H "content-type: application/json" \
-d '{"path":"/models/simple-json.zip"}' \
http://localhost:65327/model
``` 

This gives me the following error in my docker container:

```
[ERROR] [05/18/2017 20:03:49.227] [MleapServing-akka.actor.default-dispatcher-10] [MleapResource] error with request
java.nio.file.NoSuchFileException: bundle.json
	at com.sun.nio.zipfs.ZipFileSystem.newByteChannel(ZipFileSystem.java:636)
	at com.sun.nio.zipfs.ZipPath.newByteChannel(ZipPath.java:739)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newByteChannel(ZipFileSystemProvider.java:255)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.Files.readAllBytes(Files.java:3152)
	at ml.combust.bundle.BundleFile$$anonfun$readInfo$1.apply(BundleFile.scala:59)
	at ml.combust.bundle.BundleFile$$anonfun$readInfo$1.apply(BundleFile.scala:59)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.BundleFile.readInfo(BundleFile.scala:59)
	at ml.combust.bundle.serializer.BundleSerializer.read(BundleSerializer.scala:49)
	at ml.combust.bundle.BundleFile.load(BundleFile.scala:83)
	at ml.combust.mleap.runtime.MleapSupport$MleapBundleFileOps.loadMleapBundle(MleapSupport.scala:20)
	at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2$$anonfun$apply$2.apply(MleapService.scala:28)
	at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2$$anonfun$apply$2.apply(MleapService.scala:27)
	at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:88)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
	at scala.util.control.Exception$Catch.apply(Exception.scala:103)
	at scala.util.control.Exception$Catch.either(Exception.scala:125)
	at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:88)
	at resource.ManagedResourceOperations$class.apply(ManagedResourceOperations.scala:26)
	at resource.AbstractManagedResource.apply(AbstractManagedResource.scala:50)
	at resource.DeferredExtractableManagedResource$$anonfun$tried$1.apply(AbstractManagedResource.scala:33)
	at scala.util.Try$.apply(Try.scala:192)
	at resource.DeferredExtractableManagedResource.tried(AbstractManagedResource.scala:33)
	at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2.apply(MleapService.scala:29)
	at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2.apply(MleapService.scala:29)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[ERROR] [05/18/2017 20:03:49.245] [MleapServing-akka.actor.default-dispatcher-10] [akka.actor.ActorSystemImpl(MleapServing)] Error during processing of request: 'bundle.json'. Completing with 500 Internal Server Error response.
```

**Comment by hollinwilkins** [comment] 2017-05-25 15:52
@smaxwellstewart Hey,

Can you run your code again, but modify it like so:

```
(for(bundle <- managed(BundleFile("jar:file:/tmp/simple-json.zip"))) yield {
  pipeline.writeBundle.format(SerializationFormat.Json).save(bundle)
}).tried.get
```

This will allow us to see the actual error occurring during serialization.

**Comment by hollinwilkins** [comment] 2017-05-25 15:54
@smaxwellstewart I will be taking a look at this today. Thank you for the code samples.

**Comment by hollinwilkins** [comment] 2017-05-25 16:01
@smaxwellstewart I cannot reproduce this with MLeap 0.7.0, here is the code I used:


```
package org.apache.spark.mllib.clustering.bundle.tree.clustering

import ml.combust.bundle.BundleFile
import ml.combust.bundle.serializer.SerializationFormat
import ml.combust.mleap.spark.SparkSupport._
import org.apache.spark.ml.feature.{StringIndexerModel, VectorAssembler}
import org.apache.spark.ml.mleap.SparkUtil
import resource._

/**
  * Created by hollinwilkins on 5/25/17.
  */
object RunTest extends App {
  // Create a sample pipeline that we will serialize
  // And then deserialize using various formats
  val stringIndexer = new StringIndexerModel(labels = Array("Hello, MLeap!", "Another row")).
    setInputCol("a_string").
    setOutputCol("a_string_index")
  val featureAssembler = new VectorAssembler().setInputCols(Array("a_double")).
    setOutputCol("features")

  // Because of Spark's privacy, our example pipeline is considerably
  // Less interesting than the one we used to demonstrate MLeap serialization
  val pipeline = SparkUtil.createPipelineModel(Array(stringIndexer, featureAssembler))

  (for(bundle <- managed(BundleFile("jar:file:/tmp/simple-json.zip"))) yield {
    pipeline.writeBundle.format(SerializationFormat.Json).save(bundle).get
  }).tried.get
}
```

I did run into an error when I had my Spark dependencies marked as provided, but other than that I could not find a problem. How are you running your code? On the command line or on a local Spark cluster? More environment information would be helpful.

Thank you!

**Comment by hollinwilkins** [comment] 2017-05-25 16:02
Also, try changing your serialization code to this:
```
(for(bundle <- managed(BundleFile("jar:file:/tmp/simple-json.zip"))) yield {
    pipeline.writeBundle.format(SerializationFormat.Json).save(bundle).get
  }).tried.get
```

It will help surface any errors.

**Comment by smaxwellstewart** [comment] 2017-05-31 17:30
Hi,

Thanks for looking at this. In the end I did get my code working, this is what I ended up using in the end.

```scala
import ml.combust.bundle.BundleFile
import ml.combust.bundle.serializer.SerializationFormat
import org.apache.spark.ml.feature.{StringIndexerModel, VectorAssembler}
import org.apache.spark.ml.mleap.SparkUtil
import ml.combust.mleap.spark.SparkSupport._
import resource._

// Create a sample pipeline that we will serialize
// And then deserialize using various formats
val stringIndexer = new StringIndexerModel(labels = Array("Hello, MLeap!", "Another row")).
  setInputCol("a_string").
  setOutputCol("a_string_index")
val featureAssembler = new VectorAssembler().setInputCols(Array("a_string_index")).
  setOutputCol("features")

// create pipeline that will transform data
val pipeline = SparkUtil.createPipelineModel(Array(stringIndexer, featureAssembler))

// write to tmp storage
for(bundle <- managed(BundleFile("jar:file:/tmp/simple.json.zip"))) {
  pipeline.writeBundle.format(SerializationFormat.Json).save(bundle)
}
```

**Comment by manugarri** [comment] 2017-06-03 15:23
thanks @smaxwellstewart ill check that last serialization snippet and let you know!

**Comment by hollinwilkins** [comment] 2017-06-10 20:30
@manugarri Can we close this ticket out or are you still having issues with this?

**Comment by manugarri** [comment] 2017-06-11 14:41
@hollinwilkins unfortunately I am still experiencing the same error than before even when using @smaxwellstewart snippet. 

```[ERROR] [06/11/2017 16:37:27.385] [MleapServing-akka.actor.default-dispatcher-4] [MleapResource] error with request
java.nio.file.NoSuchFileException: bundle.json
        at com.sun.nio.zipfs.ZipFileSystem.newInputStream(ZipFileSystem.java:544)
        at com.sun.nio.zipfs.ZipPath.newInputStream(ZipPath.java:645)
        at com.sun.nio.zipfs.ZipFileSystemProvider.newInputStream(ZipFileSystemProvider.java:278)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at ml.combust.bundle.BundleFile$$anonfun$readInfo$1.apply(BundleFile.scala:60)
        at ml.combust.bundle.BundleFile$$anonfun$readInfo$1.apply(BundleFile.scala:60)
        at resource.DefaultManagedResource.open(AbstractManagedResource.scala:110)
        at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:87)
        at resource.ManagedResourceOperations$class.apply(ManagedResourceOperations.scala:26)
        at resource.AbstractManagedResource.apply(AbstractManagedResource.scala:50)
        at resource.DeferredExtractableManagedResource$$anonfun$tried$1.apply(AbstractManagedResource.scala:33)
        at scala.util.Try$.apply(Try.scala:192)
        at resource.DeferredExtractableManagedResource.tried(AbstractManagedResource.scala:33)
        at ml.combust.bundle.BundleFile.readInfo(BundleFile.scala:63)
        at ml.combust.bundle.serializer.BundleSerializer.read(BundleSerializer.scala:49)
        at ml.combust.bundle.BundleFile.load(BundleFile.scala:87)
        at ml.combust.mleap.runtime.MleapSupport$MleapBundleFileOps.loadMleapBundle(MleapSupport.scala:18)
        at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2$$anonfun$apply$2.apply(MleapService.scala:28)
        at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2$$anonfun$apply$2.apply(MleapService.scala:27)
        at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:88)
        at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
        at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
        at scala.util.control.Exception$Catch.apply(Exception.scala:103)
        at scala.util.control.Exception$Catch.either(Exception.scala:125)
        at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:88)
        at resource.ManagedResourceOperations$class.apply(ManagedResourceOperations.scala:26)
        at resource.AbstractManagedResource.apply(AbstractManagedResource.scala:50)
        at resource.DeferredExtractableManagedResource$$anonfun$tried$1.apply(AbstractManagedResource.scala:33)
        at scala.util.Try$.apply(Try.scala:192)
        at resource.DeferredExtractableManagedResource.tried(AbstractManagedResource.scala:33)
        at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2.apply(MleapService.scala:29)
        at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2.apply(MleapService.scala:29)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[ERROR] [06/11/2017 16:37:27.385] [MleapServing-akka.actor.default-dispatcher-4] [akka.actor.ActorSystemImpl(MleapServing)] Error during processing of request: 'bundle.json'. Completing with 500 Internal Server Error response.
```

Maybe the issue how I am launching the mleap server. I am not using docker, but instead I am starting the server by doing

```
git clone https://github.com/combust/mleap
cd mleap
git submodule init
git submodule update
sbt mleap-serving/universal:packageZipTarball
mleap-serving/target/universal/mleap-serving-0.6.0-SNAPSHOT/bin/mleap-serving
```

Maybe that is the issue?

**Comment by hollinwilkins** [comment] 2017-06-11 16:45
@manugarri I think I see the problem. You are using the mleap-serving-0.6.0-SNAPSHOT instead of mleap-serving-0.7.0 or mleap-serving-0.8.0-SNAPSHOT.

Make sure that you are using 0.7.0 when you generate the model and 0.7.0 when you load the model into the server.

Same goes for 0.8.0-SNAPSHOT, make sure your version match. Sometimes we break backwards compatibility between MLeap versions. We will enforce backwards compatibility with the release of 1.0.0.

Let me know if this helps

**Comment by manugarri** [comment] 2017-06-11 23:44
@hollinwilkins I pulled from the repo, and tried to rebuild the project, however, the only executable script is still 0.6,  how can I modify the build configuration so it also produces a 0.7 `mleap-serving` script?

**Comment by jfgosselin** [comment] 2018-02-14 21:49
Is there a workaround for this issue ? I've tried with 0.9.2 an I get the same error ...

**Comment by jfgosselin** [comment] 2018-02-14 23:23
[This ](https://github.com/combust/mleap-docs/blob/master/troubleshooting.md) solved my issue.  I know get the bundle.json in the zip file.

**Comment by hollinwilkins** [comment] 2018-03-16 14:14
Closing this issue. Executable scripts can be found in the mleap-service submodule or on dockerhub in our prebuilt docker images.

**Closed by hollinwilkins** 2018-03-16 14:14 UTC
