### ISSUE TITLE
Getting error while running sbt compile

### ISSUE THREAD

**Issue by vidit-bhatia** [combust/mleap#228] opened 2017-06-12 21:14 UTC
I am trying to build mleap using [documentation](http://mleap-docs.combust.ml/getting-started/building.html) . Unfortunately it is giving me errors in case of mlliblocal dependency.

'
Traceback (most recent call last):
  File "C:\Users\vibhatia\AppData\Local\Temp\protocbridge4017278385820396292.py"
, line 6, in <module>
    s.sendall(content)
TypeError: a bytes-like object is required, not 'str'
[info] Resolving jline#jline;2.12.1 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.apache.spark#spark-mllib-local_2.11;2.1.0: several problems occur
red while resolving dependency: org.apache.spark#spark-mllib-local_2.11;2.1.0 {c
ompile=[default(compile)]}:
[warn]  several problems occurred while resolving dependency: org.apache.spark#s
park-parent_2.11;2.1.0 {}:
[warn]  several problems occurred while resolving dependency: org.apache#apache;
14 {}:
[warn]  URI has an authority component
[warn]  URI has an authority component
[warn]
[warn]  URI has an authority component
[warn]
[warn]  URI has an authority component
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          org.apache.spark:spark-mllib-local_2.11:2.1.0 (E:\git\mleap\mlea
p-core\build.sbt#L4-5)
[warn]            +- ml.combust.mleap:mleap-core_2.11:0.8.0-SNAPSHOT
java.lang.RuntimeException: protoc returned exit code: 1
        at scala.sys.package$.error(package.scala:27)
        at sbtprotoc.ProtocPlugin$.sbtprotoc$ProtocPlugin$$compile(ProtocPlugin.
scala:114)
        at sbtprotoc.ProtocPlugin$$anonfun$sourceGeneratorTask$1$$anonfun$4.appl
y(ProtocPlugin.scala:141)
        at sbtprotoc.ProtocPlugin$$anonfun$sourceGeneratorTask$1$$anonfun$4.appl
'

Can someone please help me understand what am I doing wrong.

**Comment by matw** [comment] 2017-07-10 20:31
@vidit-bhatia Might be a bit late to help, but I had a very similar error involving spark-mllib-local when trying to compile the MLeap project. Deleting `~/.ivy2/cache/org.apache.spark/spark-mllib-local_2.11` solved this for me.

So maybe your Ivy2 cache got corrupted like mine.

**Comment by calinrc** [comment] 2017-08-01 10:29
The problem is windows representation for sbt local maven repository.
In Common.scala code there is specified local maven repo as : 

"Local Maven Repository" at "file://" + Path.userHome.absolutePath + "/.m2/repository"

This works fine for Linux path (e.g. file:///home/myuser/.m2/repository )but in case of windows one this doesn't. (file://C:/User/myuser/.m2/repository is not correct uri . Correct one would be file:///C:/User/myuser/.m2/repository (notice triple slash after file:)
) 
If you change in that sbt scala file the item into "Local Maven Repository" at "file**:///**" + Path.userHome.absolutePath + "/.m2/repository" will work fine for local sbt under windows but will break Linux build and also importing the project from some IDE (e.g. Intellij )(even under windows ) will fail with this change.
The solution here is to use sbt internal specification for local maven repository "Resolver.mavenLocal"

So just replace  
    resolvers += "Local Maven Repository" at "file://" + Path.userHome.absolutePath + "/.m2/repository",
with 
   resolvers += Resolver.mavenLocal,

**Comment by hollinwilkins** [comment] 2017-09-26 02:50
Closing this issue, the build files now properly reference Resolver.mavenLocal

**Closed by hollinwilkins** 2017-09-26 02:50 UTC
