### ISSUE TITLE
ml.combust.mleap.json fails to write null values

### ISSUE THREAD

**Issue by xhook** [combust/mleap#208] opened 2017-05-10 15:28 UTC
The following code will fail with `scala.MatchError` exception. It expects `None` instead of `null`.
```
import ml.combust.mleap.runtime.types._
import ml.combust.mleap.runtime.{LeapFrame, LocalDataset, Row}

object NullBug {

  def main(args: Array[String]): Unit = {
    val schema = StructType(
      StructField("id", IntegerType(true))
    ).get
    val dataset = LocalDataset(Row(null))
    val frame = LeapFrame(schema, dataset)
    frame.writer("ml.combust.mleap.json").toBytes().get
  }

}
```
Stacktrace:
```
Exception in thread "main" scala.MatchError: null
	at spray.json.StandardFormats$OptionFormat.write(StandardFormats.scala:33)
	at spray.json.StandardFormats$OptionFormat.write(StandardFormats.scala:32)
	at ml.combust.mleap.json.RowFormat$$anonfun$4.apply(RowFormat.scala:19)
	at ml.combust.mleap.json.RowFormat$$anonfun$4.apply(RowFormat.scala:18)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at ml.combust.mleap.json.RowFormat.write(RowFormat.scala:17)
	at ml.combust.mleap.json.DatasetFormat$$anonfun$1.apply(DatasetFormat.scala:65)
	at ml.combust.mleap.json.DatasetFormat$$anonfun$1.apply(DatasetFormat.scala:65)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at ml.combust.mleap.json.DatasetFormat.write(DatasetFormat.scala:65)
	at ml.combust.mleap.json.JsonSupport$$anon$14.write(JsonSupport.scala:174)
	at ml.combust.mleap.json.JsonSupport$$anon$14.write(JsonSupport.scala:171)
	at spray.json.PimpedAny.toJson(package.scala:39)
	at ml.combust.mleap.json.DefaultFrameWriter$$anonfun$toBytes$1.apply(DefaultFrameWriter.scala:17)
	at ml.combust.mleap.json.DefaultFrameWriter$$anonfun$toBytes$1.apply(DefaultFrameWriter.scala:17)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.mleap.json.DefaultFrameWriter.toBytes(DefaultFrameWriter.scala:17)
	at com.transferwise.fraud.ml.NullBug$.main(NullBug.scala:14)
	at com.transferwise.fraud.ml.NullBug.main(NullBug.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

I suppose `null`s should be converted to `None`s before passing to spray.json somewhere around https://github.com/combust/mleap/blob/master/mleap-runtime/src/main/scala/ml/combust/mleap/json/RowFormat.scala#L19.

**Comment by hollinwilkins** [comment] 2017-05-10 16:30
@xhook Hey,

This is by design for the moment. If you have a nullable field, then it should be an option.

I think that @varunkrmodi is looking at how MLeap handles nullable fields, so would be interested to hear what he has to say on how to handle nulls moving forward as well.

**Comment by xhook** [comment] 2017-05-12 09:35
Hi @hollinwilkins,
I see that there should be some kind of design decision made. As I understand the main requirement is to be compatible with Spark in this sense, right?

**Comment by hollinwilkins** [comment] 2017-05-25 15:40
@xhook Yes, we want to be compatible with Spark to be sure. I somewhat regret the way I implemented nulls and will probably change it before releasing MLeap 1.0.0.

**Comment by hollinwilkins** [comment] 2017-05-25 15:41
I am adding this ticket to the current 0.8.0 release to at least come up with a strategy moving forward. I know that @varunkrmodi had some good thoughts on this issue.

**Comment by hollinwilkins** [comment] 2017-06-10 20:32
@xhook Looking closer at this, Spark doesn't really support null values for any of their ML transformers. The imputer uses Double.NaN. Strings are the only values where any of the transformers check for null, which the one that comes to mind is StringIndexer. I'm going to close this issue, as I think that MLeap's null handling at this point is a superset of Spark's.

**Closed by hollinwilkins** 2017-06-10 20:32 UTC
Labels: bug, enhancement
