### ISSUE TITLE
Issue in deserializing protobuf models > 64MB

### ISSUE THREAD

**Issue by saurabh3949** [combust/mleap#164] opened 2017-04-04 00:30 UTC
Hi,
I was trying to load a big MultiLayer perceptron bundle into Mleap serving. It throws the following error:

[ERROR] [04/03/2017 23:57:48.917] [MleapServing-akka.actor.default-dispatcher-89] [MleapResource] error with request
com.google.protobuf.InvalidProtocolBufferException: Protocol message was too large.  May be malicious.  Use CodedInputStream.setSizeLimit() to increase the size limit.
	at com.google.protobuf.InvalidProtocolBufferException.sizeLimitExceeded(InvalidProtocolBufferException.java:134)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readRawBytesSlowPath(CodedInputStream.java:2768)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readBytes(CodedInputStream.java:2335)
	at ml.bundle.Tensor.Tensor.mergeFrom(Tensor.scala:92)
	at ml.bundle.Tensor.Tensor.mergeFrom(Tensor.scala:11)
	at com.trueaccord.scalapb.LiteParser$.readMessage(LiteParser.scala:15)
	at ml.bundle.Value.Value.mergeFrom(Value.scala:94)
	at ml.bundle.Value.Value.mergeFrom(Value.scala:13)
	at com.trueaccord.scalapb.LiteParser$.readMessage(LiteParser.scala:15)
	at ml.bundle.Attribute.Attribute.mergeFrom(Attribute.scala:54)
	at ml.bundle.Attribute.Attribute.mergeFrom(Attribute.scala:11)
	at com.trueaccord.scalapb.LiteParser$.readMessage(LiteParser.scala:15)
	at ml.bundle.AttributeList.AttributeList$AttributesEntry.mergeFrom(AttributeList.scala:131)
	at ml.bundle.AttributeList.AttributeList$AttributesEntry.mergeFrom(AttributeList.scala:87)
	at com.trueaccord.scalapb.LiteParser$.readMessage(LiteParser.scala:15)
	at ml.bundle.AttributeList.AttributeList.mergeFrom(AttributeList.scala:44)
	at ml.bundle.AttributeList.AttributeList.mergeFrom(AttributeList.scala:11)
	at com.trueaccord.scalapb.LiteParser$.parseFrom(LiteParser.scala:9)
	at com.trueaccord.scalapb.GeneratedMessageCompanion$class.parseFrom(GeneratedMessageCompanion.scala:121)
	at ml.bundle.AttributeList.AttributeList$.parseFrom(AttributeList.scala:65)
	at com.trueaccord.scalapb.GeneratedMessageCompanion$class.parseFrom(GeneratedMessageCompanion.scala:123)
	at ml.bundle.AttributeList.AttributeList$.parseFrom(AttributeList.scala:65)
	at ml.combust.bundle.serializer.attr.AttributeListSerializer$$anonfun$readProto$2.apply(AttributeListSerializer.scala:92)
	at ml.combust.bundle.serializer.attr.AttributeListSerializer$$anonfun$readProto$2.apply(AttributeListSerializer.scala:91)
	at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:88)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
	at scala.util.control.Exception$Catch.apply(Exception.scala:103)
	at scala.util.control.Exception$Catch.either(Exception.scala:125)
	at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:88)
	at resource.ManagedResourceOperations$class.apply(ManagedResourceOperations.scala:26)
	at resource.AbstractManagedResource.apply(AbstractManagedResource.scala:50)
	at resource.DeferredExtractableManagedResource$$anonfun$tried$1.apply(AbstractManagedResource.scala:33)
	at scala.util.Try$.apply(Try.scala:192)
	at resource.DeferredExtractableManagedResource.tried(AbstractManagedResource.scala:33)
	at ml.combust.bundle.serializer.attr.AttributeListSerializer.readProto(AttributeListSerializer.scala:93)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$readWithModel$3.apply(ModelSerializer.scala:133)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$readWithModel$3.apply(ModelSerializer.scala:126)
	at scala.util.Success.flatMap(Try.scala:231)
	at ml.combust.bundle.serializer.ModelSerializer.readWithModel(ModelSerializer.scala:125)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$read$3.apply(NodeSerializer.scala:110)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$read$3.apply(NodeSerializer.scala:109)
	at scala.util.Success.flatMap(Try.scala:231)
	at ml.combust.bundle.serializer.NodeSerializer.read(NodeSerializer.scala:108)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$readNode$2.apply(GraphSerializer.scala:57)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$readNode$2.apply(GraphSerializer.scala:57)
	at scala.util.Success.flatMap(Try.scala:231)
	at ml.combust.bundle.serializer.GraphSerializer.readNode(GraphSerializer.scala:56)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$read$1.apply(GraphSerializer.scala:44)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$read$1.apply(GraphSerializer.scala:44)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at ml.combust.bundle.serializer.GraphSerializer.read(GraphSerializer.scala:44)
	at ml.combust.mleap.bundle.ops.PipelineOp$$anon$1.load(PipelineOp.scala:27)
	at ml.combust.mleap.bundle.ops.PipelineOp$$anon$1.load(PipelineOp.scala:14)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$readWithModel$3$$anonfun$apply$8.apply(ModelSerializer.scala:143)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$readWithModel$3$$anonfun$apply$8.apply(ModelSerializer.scala:142)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$readWithModel$3.apply(ModelSerializer.scala:141)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$readWithModel$3.apply(ModelSerializer.scala:126)
	at scala.util.Success.flatMap(Try.scala:231)
	at ml.combust.bundle.serializer.ModelSerializer.readWithModel(ModelSerializer.scala:125)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$read$3.apply(NodeSerializer.scala:110)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$read$3.apply(NodeSerializer.scala:109)
	at scala.util.Success.flatMap(Try.scala:231)
	at ml.combust.bundle.serializer.NodeSerializer.read(NodeSerializer.scala:108)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$readNode$2.apply(GraphSerializer.scala:57)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$readNode$2.apply(GraphSerializer.scala:57)
	at scala.util.Success.flatMap(Try.scala:231)
	at ml.combust.bundle.serializer.GraphSerializer.readNode(GraphSerializer.scala:56)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$read$1.apply(GraphSerializer.scala:44)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$read$1.apply(GraphSerializer.scala:44)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at ml.combust.bundle.serializer.GraphSerializer.read(GraphSerializer.scala:44)
	at ml.combust.mleap.bundle.ops.PipelineOp$$anon$1.load(PipelineOp.scala:27)
	at ml.combust.mleap.bundle.ops.PipelineOp$$anon$1.load(PipelineOp.scala:14)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$readWithModel$3$$anonfun$apply$8.apply(ModelSerializer.scala:143)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$readWithModel$3$$anonfun$apply$8.apply(ModelSerializer.scala:142)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$readWithModel$3.apply(ModelSerializer.scala:141)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$readWithModel$3.apply(ModelSerializer.scala:126)
	at scala.util.Success.flatMap(Try.scala:231)
	at ml.combust.bundle.serializer.ModelSerializer.readWithModel(ModelSerializer.scala:125)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$read$3.apply(NodeSerializer.scala:110)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$read$3.apply(NodeSerializer.scala:109)
	at scala.util.Success.flatMap(Try.scala:231)
	at ml.combust.bundle.serializer.NodeSerializer.read(NodeSerializer.scala:108)
	at ml.combust.bundle.serializer.BundleSerializer$$anonfun$read$2.apply(BundleSerializer.scala:56)
	at ml.combust.bundle.serializer.BundleSerializer$$anonfun$read$2.apply(BundleSerializer.scala:49)
	at scala.util.Success.flatMap(Try.scala:231)
	at ml.combust.bundle.serializer.BundleSerializer.read(BundleSerializer.scala:49)
	at ml.combust.bundle.BundleFile.load(BundleFile.scala:87)
	at ml.combust.mleap.runtime.MleapSupport$MleapBundleFileOps.loadMleapBundle(MleapSupport.scala:20)
	at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2$$anonfun$apply$2.apply(MleapService.scala:28)
	at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2$$anonfun$apply$2.apply(MleapService.scala:27)
	at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:88)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
	at scala.util.control.Exception$Catch.apply(Exception.scala:103)
	at scala.util.control.Exception$Catch.either(Exception.scala:125)
	at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:88)
	at resource.ManagedResourceOperations$class.apply(ManagedResourceOperations.scala:26)
	at resource.AbstractManagedResource.apply(AbstractManagedResource.scala:50)
	at resource.DeferredExtractableManagedResource$$anonfun$tried$1.apply(AbstractManagedResource.scala:33)
	at scala.util.Try$.apply(Try.scala:192)
	at resource.DeferredExtractableManagedResource.tried(AbstractManagedResource.scala:33)
	at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2.apply(MleapService.scala:29)
	at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2.apply(MleapService.scala:29)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by hollinwilkins** [comment] 2017-04-04 03:47
@saurabh3949 Hey,

Thank you for the bug report. I think this should be an easy fix by modifying this line here to use a CodedInputStream with the size limit increased:
https://github.com/combust/mleap/blob/master/bundle-ml/src/main/scala/ml/combust/bundle/serializer/ModelSerializer.scala#L66

**Comment by hollinwilkins** [comment] 2017-04-12 17:27
@saurabh3949 I can't actually reproduce this error. I am making a tensor that is 128MB, serializing it, then deserializing it without issue. What version of MLeap was this? It may have been fixed when we upgrade scalapb.

**Comment by hollinwilkins** [comment] 2017-04-21 04:31
Closing this for now, please reopen if you run into this issue again or have more information.

**Comment by Mageswaran1989** [comment] 2017-05-25 11:17
@hollinwilkins hi, any improvements on this issue? we have a 'model.pb' of size 200MB which stops the whole pipeline loading.

While debugging it says : (At Line#88 in AbstractManagedResource.scala)
Left(com.google.protobuf.InvalidProtocolBufferException: Protocol message was too large.  May be malicious.  Use CodedInputStream.setSizeLimit() to increase the size limit.)

**Comment by Mageswaran1989** [comment] 2017-05-25 12:32
@hollinwilkins looks like we have found the solution! 

will update after some testing :)

**Comment by hollinwilkins** [comment] 2017-05-25 15:34
@Mageswaran1989 That would be great! I tried to recreate this issue and could not. Put in a PR for the fix and we'll get it in.

Thanks

**Comment by hollinwilkins** [comment] 2017-09-26 02:41
Closing this issue as there was a PR to fix it.

**Closed by hollinwilkins** 2017-09-26 02:41 UTC
Labels: bug
