### ISSUE TITLE
Apache Spark MLlib GBTClassifier import from JSON bundle fails

### ISSUE THREAD

**Issue by jkbradley** [combust/mleap#517] opened 2019-04-19 21:46 UTC
Short version:
* I exported an MLlib Pipeline with a GBTClassificationModel
* I inspected the bundle JSON, and it looked correct.
* I import the bundle, and the GBTClassificationModel's tree models had all-0 predictions.

Environment:
* Apache Spark 2.4 (in Databricks, using DBR 5.3 ML)
* Maven MLeap: `ml.combust.mleap:mleap-databricks-runtime_2.11:0.13.0`
* PyPi MLeap: 0.8.1 https://pypi.org/project/mleap/
* Used PySpark and Python MLeap API

Reproduction:
```
from pyspark.ml import Pipeline, PipelineModel
from pyspark.ml.classification import GBTClassifier
from pyspark.ml.linalg import Vectors
from pyspark.ml.feature import StringIndexer

import mleap.pyspark
from mleap.pyspark.spark_support import SimpleSparkSerializer

df = spark.createDataFrame([
  (1.0, Vectors.dense(1.0)),
  (0.0, Vectors.sparse(1, [], []))
], ["label", "features"])

stringIndexer = StringIndexer(inputCol="label", outputCol="indexed")
gbt = GBTClassifier(maxIter=2, maxDepth=1, labelCol="indexed", seed=42)
pipeline = Pipeline(stages=[stringIndexer, gbt])

model = pipeline.fit(df)

MODEL_FILE = "jar:file:/home/ubuntu/my_gbt_pipeline.zip"
model.serializeToBundle(MODEL_FILE, model.transform(df))

loadedModel = PipelineModel.deserializeFromBundle(MODEL_FILE)

model.transform(df).show()

loadedModel.transform(df).show()  # DIFFERENT
```

Note: I tried loading the bundle back in the Scala MLeap API but ran into the same issue with all-0 predictions for the underlying regression trees in the GBT model.

**Comment by ancasarb** [comment] 2019-05-03 12:58
This issue is actually caused by the bug described here https://github.com/combust/mleap/issues/506.  We'll try to fix it and get it merged as part of https://github.com/combust/mleap/pull/522. Thanks @jkbradley for raising this issue!

**Comment by ancasarb** [comment] 2019-05-07 12:54
PR has been merged and will be released as part of the new mleap release.

**Closed by ancasarb** 2019-05-07 12:54 UTC
Labels: bug
