### ISSUE TITLE
Scikit Linear Regression Serialization Issue

### ISSUE THREAD

**Issue by siddhant0509** [combust/mleap#331] opened 2018-02-07 14:11 UTC
Linear Regression Serialization fails with error

Error
File "/Library/Python/2.7/site-packages/mleap/sklearn/pipeline.py", line 29, in serialize_to_bundle
    serializer.serialize_to_bundle(self, path, model_name, init)
  File "/Library/Python/2.7/site-packages/mleap/sklearn/pipeline.py", line 107, in serialize_to_bundle
    step_i.serialize_to_bundle(bundle_dir, step_i.name)
  File "/Library/Python/2.7/site-packages/mleap/sklearn/base.py", line 27, in serialize_to_bundle
    return serializer.serialize_to_bundle(self, path, model_name)
  File "/Library/Python/2.7/site-packages/mleap/sklearn/base.py", line 64, in serialize_to_bundle
    attributes.append(('intercept', transformer.intercept_.tolist()[0]))
TypeError: 'float' object has no attribute '__getitem__'

**Comment by siddhant0509** [comment] 2018-02-07 16:56
Sample 
import pandas as pd

import mleap.sklearn.pipeline
import mleap.sklearn.base
from mleap.sklearn.preprocessing.data import FeatureExtractor
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn import datasets
import numpy as np

diabetes = datasets.load_diabetes()
diabetes_X = diabetes.data[:, np.newaxis, 2]
diabetes_X_train = diabetes_X[:-20]
diabetes_X_test = diabetes_X[-20:]
diabetes_y_train = diabetes.target[:-20]
diabetes_y_test = diabetes.target[-20:]
df = pd.DataFrame(diabetes_X_train, columns=['x'])
feature_extractor_tf = FeatureExtractor(input_scalars=['x'], output_vector='unscaled_cont_features', output_vector_items=["scaled_{}".format(x) for x in ['x']])
feature_extractor_tf.skip_fit_transform = True
lr_model = LinearRegression()
lr_model.mlinit(input_features='unscaled_cont_features', prediction_column='price_prediction')
lr_model_pipeline = Pipeline([
        (feature_extractor_tf.name, feature_extractor_tf),
        (lr_model.name, lr_model)
    ])
lr_model_pipeline.mlinit()
lr_model_pipeline.fit(diabetes_X_train,diabetes_y_train)
print lr_model_pipeline
lr_model_pipeline.serialize_to_bundle('/tmp', 'diabetes', init=True)

**Comment by hollinwilkins** [comment] 2018-03-16 14:31
@ancasarb Is there anything obvious here about what's going on?

**Comment by ancasarb** [comment] 2018-03-17 15:10
@siddhant0509 @hollinwilkins 
it looks like during fitting, scikit's linear regression will: 
- set 'transformer.intercept_' to a float value, if the X, y passed in are numpy.ndarray(s) 
- set 'transformer.intercept_' to a numpy.ndarray, if the X, y passed in are pandas.Dataframe(s)

During the serialize_to_bundle() for the linear regression, it looks like we assume they'll be numpy.ndarray(s)

```
attributes.append(('intercept', transformer.intercept_.tolist()[0]))
attributes.append(('coefficients', transformer.coef_.tolist()[0])) 
```

I will take a look at changing this so that it works in both cases, however for now, just simply transforming the X, y passed to the linear regression will get this to work. 

``` 
df = pd.DataFrame(diabetes_X_train, columns=['x'])
y = pd.DataFrame(diabetes_y_train, columns=['y'])

.... (and later)
lr_model_pipeline.fit(df, y)
```

**Comment by ancasarb** [comment] 2019-03-03 16:48
Closing this for now, as the workaround is quite easy to do.

**Closed by ancasarb** 2019-03-03 16:48 UTC
